const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{paisagem: 0},
	{Sólido: 0},
	{terra1: 0},
	{terra2: 0},
	{terra3: 0},
	{terra4: 0},
	{arvore: 0},
	{Plataforma: 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{Personagem: 0},
	{cogularanja: 0},
	{caixas: 0},
	{cogurosa: 0},
	{arbusto: 0},
	{água: 0},
	{pedra: 0},
	{contagem: 0},
	{coleteOsCogumelos: 0},
	{vida: 0},
	{contagensDeVida: 0},
	{Áudio: 0},
	{c287c6c24f813777f1ec501d2d19ddc: 0},
	{letreiro: 0},
	{Mouse: 0},
	{Solid: 0},
	{start: 0},
	{cemiterio: 0},
	{b913fd8175a50a58483b34a3d524c: 0},
	{c5b14610017184e29293562a1088b: 0},
	{Derrota: 0},
	{af47e28b0d1638ab04f81a0f: 0},
	{TryAgain: 0},
	{Sim: 0},
	{Não: 0},
	{manilaropecutoutisolatedropeontransparentbackgroundpng: 0},
	{TiledBackground: 0},
	{ForestandTreesFreePixelBackgrounds: 0},
	{xao: 0},
	{Platform: 0},
	{inimigo: 0},
	{barreira: 0},
	{escad: 0},
	{tronco: 0},
	{chavefim: 0},
	{portafim: 0},
	{Sine: 0},
	{Sprite: 0},
	{f66c67761701a58fb38814eb17397c: 0},
	{cde3ed5d6974370dcd958f61baa15f: 0},
	{e68641665722e6a914e97b69dbdda: 0},
	{Sprite2: 0},
	{Sprite3: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	paisagem: class extends self.ISpriteInstance {},
	terra1: class extends self.ISpriteInstance {},
	terra2: class extends self.ISpriteInstance {},
	terra3: class extends self.ISpriteInstance {},
	terra4: class extends self.ISpriteInstance {},
	arvore: class extends self.ISpriteInstance {},
	Personagem: class extends self.ISpriteInstance {},
	cogularanja: class extends self.ISpriteInstance {},
	caixas: class extends self.ISpriteInstance {},
	cogurosa: class extends self.ISpriteInstance {},
	arbusto: class extends self.ISpriteInstance {},
	água: class extends self.ISpriteInstance {},
	pedra: class extends self.ISpriteInstance {},
	contagem: class extends self.ISpriteFontInstance {},
	coleteOsCogumelos: class extends self.ISpriteFontInstance {},
	vida: class extends self.ISpriteInstance {},
	contagensDeVida: class extends self.ISpriteFontInstance {},
	Áudio: class extends self.IInstance {},
	c287c6c24f813777f1ec501d2d19ddc: class extends self.ISpriteInstance {},
	letreiro: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	start: class extends self.ISpriteInstance {},
	cemiterio: class extends self.ISpriteInstance {},
	b913fd8175a50a58483b34a3d524c: class extends self.ISpriteInstance {},
	c5b14610017184e29293562a1088b: class extends self.ISpriteInstance {},
	Derrota: class extends self.ISpriteInstance {},
	af47e28b0d1638ab04f81a0f: class extends self.ISpriteInstance {},
	TryAgain: class extends self.ISpriteInstance {},
	Sim: class extends self.ISpriteInstance {},
	Não: class extends self.ISpriteInstance {},
	manilaropecutoutisolatedropeontransparentbackgroundpng: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	ForestandTreesFreePixelBackgrounds: class extends self.ISpriteInstance {},
	xao: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	barreira: class extends self.ISpriteInstance {},
	escad: class extends self.ISpriteInstance {},
	tronco: class extends self.ISpriteInstance {},
	chavefim: class extends self.ISpriteInstance {},
	portafim: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	f66c67761701a58fb38814eb17397c: class extends self.ISpriteInstance {},
	cde3ed5d6974370dcd958f61baa15f: class extends self.ISpriteInstance {},
	e68641665722e6a914e97b69dbdda: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}